name: simple_story
description: "A new Flutter package project."
version: 0.0.1
publish_to: none
# homepage:
environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  simple_utils:
    path: ../simple_utils

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter: null
